summary:
  project: 饼盒App
  module: 帖子模块

auth_login_01:
  protocol: https
  hosts: 127.0.0.1:8080, 127.0.0.1:8080
  api: /login
  method: gET
  params:
    page_num: 1
    limit: 1
  headers:
  data:
  needValidation:
  context:
  description:

auth_login_02:
  protocol: http
  hosts: 127.0.0.1:8080
  api: /login
  method: POST
  params:
  headers:
  data:
  needValidation:
  context:
  description:


