summary:
  project: 饼盒App
  module: 帖子模块

# 需要登陆，携带token才能够查询post. 可以通过context来拿到token
post_add_01:
  protocol: http
  hosts: 127.0.0.1:50090
  api: /post
  method:  POST
  params:
  data:
    content : 没有什么内容，单纯为了凑满10个字～～
    forumId : 1
    title : 测试用的title
    summary: ""
    coverImage : ""
  headers:
    Content-Type : application/json
    token: $.response.global.token
  needValidation:
  context:
  description:
  sql:
    setup:
      persist:
      execute:
    teardown:
      persist:
      execute:
        - delete from post where post_id = %s [($.self.data.postId)]
        - delete from audit_status where audit_status_id = %s [($.self.data.auditStatusId)]

post_delete_01:
  protocol: http
  hosts: 127.0.0.1:50090
  api: /post/{$.sql.setup.persist.delete_01_post_id[0]}
  method: DelEte
  params:
  data:
    userId: $.response.module.userId
  headers:
    Content-Type: application/json
    token: $.response.global.token
  sql:
    setup:
      persist:
        delete_01_audit_status_id: insert into audit_status (audit_status) values (%s) [(1)]
        delete_01_post_id: INSERT INTO post (title, cover_image, summary, content, author_id, forum_id, audit_status_id, views, priority, created_at, updated_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) [(Test Delete Title, ABC, Test Delete Summary, Test Delete Content, $.response.module.userId, 1, $.sql.setup.persist.delete_01_audit_status_id[0], 0, 0, 2025-01-16 12:00:00, 2025-01-16 12:00:00)];










