summary:
  project: 饼盒App
  module: 帖子模块

# 需要登陆，携带token才能够查询post. 可以通过context来拿到token
post_add_01:
  protocol: http
  hosts: 127.0.0.1:50090
  api: /post
  method:  POST
  params:
  data:
    content : 没有什么内容，单纯为了凑满10个字～～
    forumId : 1
    title : 测试用的title
    summary: ""
    coverImage : ""
  headers:
    Content-Type : application/json
    token: $.response.global.token
  needValidation:
  context:
  description:
  setup_sql:
  sql:
    setup:
      persist:
      normal:
    teardown:
      persist:
      execute:



#post_delete_01:
#  protocol: http
#  host: 127.0.0.1
#  api: /post/{$.sql.post_delete_01.}
#  method: DelEte
#  param:
#  data:
#  headers:
#    Content-Type: application/json









