summary:
  project: 饼盒App
  module: 帖子模块

# 需要登陆，携带token才能够查询post. 可以通过context来拿到token
post_query_01:
  protocol: http
  hosts: 127.0.0.1:8080, 127.0.0.1:8080
  api: /api/posts/1
  method:  gET
  pathVariables:
  params:
  headers:
    Authorization: Bearer {$.response.global.token}
  needValidation:
  context:
  description:

post_query_02:
  protocol: http
  hosts: 127.0.0.1:8080, 127.0.0.1:8080
  api: /api/posts/2
  method:  gET
  pathVariables:
  params:
  headers:
    Authorization: Bearer {$.response.global.token}
  needValidation:
  context:
  description:

