summary:
  project: 饼盒App
  module: 帖子模块

# 需要登陆，携带token才能够查询post. 可以通过context来拿到token
post_query_01:
  protocol: https
  hosts: 127.0.0.1:8080, 127.0.0.1:8080
  api: /api/posts
  method:  gET
  params:
    postId: 1
  headers:
    Authorization: Bearer {$ response.global.token} qqq {$ data.qq}
  data:
  needValidation:
  context:
  description:



