summary:
  project: 饼盒App
  module: 帖子模块

# 需要登陆，携带token才能够查询post. 可以通过context来拿到token
post_add_01:
  protocol: http
  hosts: v4.concrete8.work:50090
  api: /post
  method:  POST
  params:
  data:
    content : abcdefghklm111
    forumId : 1
    title : abqqupokskala
    summary: ""
    coverImage : ""
  headers:
    Content-Type : application/json
    token: $.response.global.token
  needValidation:
  context:
  description:
  teardown_sql:




