summary:
  project: 饼盒App
  module: 登陆模块

auth_login_01:
  protocol: http
  hosts: localhost:50090, localhost:50090
  api: /user/login
  method: POST
  params:
  headers:
    Content-Type : application/json
  data:
    account: cookietest_anicaa
    password: kexin1337
  context:
    response:
      global:
        token: $.data.token
      module:
        userId: $.data.info.id
  description:
  assertion:
    assert_token_exist:
      actual: $.response.global.token
      expected:
          type: not
          value: null
      error_message: "默认apitestcase.identifier: assertionKey(在这里是assert_token_exist)断言失败"
      correct_message:

    assert_tester_userId:
      actual: $.response.module.userId
      expected:
        type: is
        value: 15860
      error_message: "默认apitestcase.identifier: assertionKey(在这里是assert_token_exist)断言失败"
      correct_message:


