summary:
  project: 饼盒App
  module: 登陆模块

auth_login_01:
  protocol: http
  hosts: 127.0.0.1:8080, 127.0.0.1:8080
  api: /api/auth/login
  method: POST
  pathVariables:
  params:
    page_num: 1
    limit: 1
  headers:
    Content-Type : application/json
  data:
    username: cookiebox_test
    password: kexin1337
  context:
    response:
      global:
        token: $.data.token
      module:
        username: $.data.userVO.username
  description:

auth_login_02:
  protocol: http
  hosts: 127.0.0.1:8080
  api: /login
  method: POST
  pathVariables:
  params:
  headers:
  data:
  context:
  description:


